### ISSUE TITLE
Error being raised on GUILD_DELETE

### ISSUE THREAD

**Issue by davfsa** [nekokatt/hikari#22]
### Steps to reproduce
1. Run the bot (make sure you have `stateless=False` in the args for the bot)
2. Remove/kick/ban the bot from a guild
3. Check console

### Traceback
Traceback provided by @Chubonyo 
```py
E 2020-08-20 01:43:48,154 asyncio: Task exception was never retrieved
future: <Task finished name='gateway shard 0 dispatch GUILD_DELETE' coro=<EventManagerBase.consume_raw_event() done, defined at C:\Users\{user}\Documents\Chub bot project\.venv\lib\site-packages\hikari\impl\event_manager_base.py:81> exception=KeyError(270904126974590976)>
Traceback (most recent call last):
  File "C:\Users\{user}\Documents\Chub bot project\.venv\lib\site-packages\hikari\impl\event_manager_base.py", line 89, in consume_raw_event
    await callback(shard, payload)
  File "C:\Users\{user}\Documents\Chub bot project\.venv\lib\site-packages\hikari\impl\stateful_event_manager.py", line 188, in on_guild_delete
    self._cache.clear_members_for_guild(event.guild_id)
  File "C:\Users\{user}\Documents\Chub bot project\.venv\lib\site-packages\hikari\impl\stateful_cache.py", line 1529, in clear_members_for_guild
    cached_users = {user_id: self._user_entries[user_id] for user_id in cached_members}
  File "C:\Users\{user}\Documents\Chub bot project\.venv\lib\site-packages\hikari\impl\stateful_cache.py", line 1529, in <dictcomp>
    cached_users = {user_id: self._user_entries[user_id] for user_id in cached_members}
KeyError: 270904126974590976
```

### System info
hikari v2.0.0.dev69

### Checklist

- [x] I have made sure to remove ANY sensitive information (bot token, passwords,
      credentials, personal details, etc).
- [x] I have searched the issue tracker and have made sure it's not a duplicate.
      If it is a follow up of another issue, I have specified it.

**Comment by nekokatt** [comment]
@FasterSpeeding is this caused by the fact discord might be sending a MEMBER_DELETE for the bot user before it receives a GUILD_DELETE event? If so, is this a Discord API bug that should be reported, or should we be able to implement handling for this? 

Just thinking because of eventual consistency it is probably worth still deleting in both places in case one event is not sent but the other is, if this is the issue.

**Comment by nekokatt** [comment]
Closing because no activity and no further reports that this has occurred. 

If you still get the issue, please ensure you are on 2.0.0.dev76 and open a new issue.
