### ISSUE TITLE
Bump pdoc3 version back to pypi releases

### ISSUE THREAD

**Issue by davfsa** [nekokatt/hikari#94]
Pdoc3 V0.9 got released about 13h ago (at the time of writing this) which includes the lunr.js search that I madr.

This should be tested that it still builds and the search bar works correctly.

**Comment by nekokatt** [comment]
Can confirm that this no longer works with our set up using v0.9.0.

```
$ nox -spdoc
nox > Running session pdoc
nox > Creating virtual environment (virtualenv) using python in .nox/pdoc
nox > pip install -r requirements.txt
nox > pip install pdoc3~=0.9.0
nox > pip install sphobjinv
nox > python docs/patched_pdoc.py hikari --html --output-dir public --template-dir docs --force
/home/me/code/hikari/.nox/pdoc/lib/python3.8/site-packages/aiohttp/helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
Traceback (most recent call last):
  File "docs/patched_pdoc.py", line 9, in <module>
    main()
  File "docs/patched_pdoc.py", line 5, in main
    cli.main()
  File "/home/me/code/hikari/.nox/pdoc/lib/python3.8/site-packages/pdoc/cli.py", line 537, in main
    modules = [pdoc.Module(module, docfilter=docfilter,
  File "/home/me/code/hikari/.nox/pdoc/lib/python3.8/site-packages/pdoc/cli.py", line 537, in <listcomp>
    modules = [pdoc.Module(module, docfilter=docfilter,
  File "/home/me/code/hikari/.nox/pdoc/lib/python3.8/site-packages/pdoc/__init__.py", line 640, in __init__
    self.doc[name] = Class(name, self, obj)
  File "/home/me/code/hikari/.nox/pdoc/lib/python3.8/site-packages/pdoc/__init__.py", line 952, in __init__
    for _name, obj in _getmembers_all(self.obj)
  File "/home/me/code/hikari/.nox/pdoc/lib/python3.8/site-packages/pdoc/__init__.py", line 907, in _getmembers_all
    names.update(_get_type_hints(obj).keys())
  File "/usr/lib/python3.8/typing.py", line 1232, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/usr/lib/python3.8/typing.py", line 270, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/lib/python3.8/typing.py", line 518, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'datetime' is not defined
```

**Comment by nekokatt** [comment]
Looks like this is blocked by https://github.com/pdoc3/pdoc/issues/245, which may or may not be a very simple fix, so for now I will leave this open and see what happens. :)

**Comment by davfsa** [comment]
https://github.com/pdoc3/pdoc/pull/246
